### ISSUE TITLE
Cannot compile on new phoenix 1.7.0

### ISSUE THREAD

**Issue by dev-rroslan** [tfwright/live_admin#28]
== Compilation error in file lib/live_admin/view.ex ==
** (CompileError) lib/live_admin/view.ex:4: module Phoenix.View is not loaded and could not be found
    (elixir 1.14.3) expanding macro: Kernel.use/2
    lib/live_admin/view.ex:4: LiveAdmin.View (module)

**Comment by tfwright** [comment]
I think adding phoenix_view as a dependency should solve this issue. See https://github.com/tfwright/live_admin/issues/13#issuecomment-1423308893

**Comment by zazaian** [comment]
Hey @dev-rroslan - Phoenix 1.7 is so structurally different in the Web module from <= 1.6.x that several meaningful changes will need to be made in order to achieve full 1.7 compatibility. Specifically, Views have been completely replaced by Components, and routing helpers have been completely reconfigured to use the new sigil verified route syntax. It looks, from the commits, that @tfwright is already working on 1.7 compatibility, but has not issued a new tagged release with those patches.

I'd keep an eye out for the next couple of tagged releases, one of which I assume should add support for Phoenix 1.7. @tfwright please correct me if I'm wrong here.

**Comment by dev-rroslan** [comment]
Hi, thanks for a quick reply. I have a use case and searching for a module
to disable registration but admin or registered user can invite. Thanks
again.

**Comment by dev-rroslan** [comment]
here's my route but not rendering the default template. I am new to Phoenix
GET     /admin                                 LiveAdmin.Components.Home :home
  GET     /admin/:resource_id                    LiveAdmin.Components.Container :list
  GET     /admin/:resource_id/new                LiveAdmin.Components.Container :new
  GET     /admin/:resource_id/edit/:record_id    LiveAdmin.Components.Container :edit

here's my scope in the router:
 scope "/admin", UndiWeb do
    live_admin "/", resources: [Undi.User]
  end

**Comment by zazaian** [comment]
Hi @dev-rroslan - are you currently upgrading from Phoenix 1.6 to 1.7? Or are you working off of a freshly-generated Phoenix 1.7 application and trying to install `live_admin` on top of that?

**Comment by tfwright** [comment]
Closing this because there's nothing to do here. @dev-rroslan for general help/advice, please use the elixir forum thread: https://elixirforum.com/t/liveadmin-phoenix-admin-ui-built-on-liveview/46421

**Comment by zazaian** [comment]
@tfwright are you planning to publish a Phoenix 1.7 compatible tagged release? At present it does not appear that installing `phoenix_view` as a dependency by itself makes `live_admin` compatible with 1.7.

**Comment by tfwright** [comment]
AFAIK it should be possible to use 1.7 but including phoenix_view and ensuring that route helpers are enabled. But if you have found other issues please open a new bug report, and if you can push a sample app that demonstrates the problem that would be greatly helpful. Thanks!

**Comment by zazaian** [comment]
Understood. I'm still running into some issues on 1.7 even with `phoenix_view` installed, and cannot load the `live-admin` index page without error. I'll post the issue I'm experiencing when I have a moment to do so.
